name: Basic Django Test with ZAP Baseline Scan

on:
  push:
    branches: [ "main", "uat" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.6]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd webguard
        python manage.py test
    - name: Run Server
      if: ${{ success() }}
      run: |
        cd webguard
        python manage.py runserver &
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:8000/'
