name: ZAP Baseline Scan

on:
  workflow_run:
    workflows: [Default Django Test]
    types:
      - completed

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies and Run Server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd djangobasic
        python manage.py runserver 0.0.0.0:8000 --noreload
    - name: ZAP Scan
      if: always()
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:8000/'
